title:              "용덕후의 인플루언서 마케팅"
tagline:            "마이크로인플루언서 핫피플 정용"
email:              "wjddyd89@gmail.com"
description:        "인플루언서 마케팅이란 무엇인가에 대한 설명과 저의 결과물에 대한 설명"
author:             "정용"
baseurl:            "/"
url:                "https://wjddyd89.github.io"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
twitter_username:   crime4135
instagram_username: wjddyd89
facebook_username:  youngduchoo

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: wjddyd89
